import collections,json,pathlib,statistics
ROOT=pathlib.Path(__file__).resolve().parents[2];OUT=ROOT/'docs/benchmarks/issue-156'
def main():
 rows=[json.loads(s) for s in (OUT/'iteration-8-results.jsonl').read_text().splitlines()]
 if len(rows)!=8:raise ValueError('incomplete_observations')
 walls=sorted(r['wall_seconds'] for r in rows);naive=[r for r in rows if 'naive_highest' in r]
 result=dict(observations=8,partition_exact=sum(r['exact'] for r in rows),exact=sum(r['exact'] for r in rows),baseline_exact=sum(r['baseline']['exact'] for r in rows),complete=sum(r['complete'] for r in rows),fm=sum(r['false_merge'] for r in rows),fs=sum(r['false_split'] for r in rows),baseline_fm=sum(r['baseline']['false_merge'] for r in rows),baseline_fs=sum(r['baseline']['false_split'] for r in rows),calls=sum(r['calls'] for r in rows),unobserved_call_tokens=sum(r['calls']>0 and (r['input_tokens'] is None or r['output_tokens'] is None) for r in rows),input_tokens_lower_bound=sum(r['input_tokens'] or 0 for r in rows),output_tokens_lower_bound=sum(r['output_tokens'] or 0 for r in rows),wall_total=sum(walls),total_wall_budget=600,total_wall_budget_pass=sum(walls)<=600,wall_mean=statistics.mean(walls),wall_p95_lower=walls[int((len(walls)-1)*.95)],reasons=dict(collections.Counter(r['reason'].split(':')[0]+(':'+r['reason'].split(':')[1] if r['reason'].startswith('ValueError:') else '') for r in rows)),naive_observations=len(naive),naive_exact=sum(r['naive_highest']['exact'] for r in naive),naive_fm=sum(r['naive_highest']['false_merge'] for r in naive) if naive else None,naive_fs=sum(r['naive_highest']['false_split'] for r in naive) if naive else None,strata={s:dict(cases=sum((r['files']<=8 if s=='5-8' else r['files']>8) for r in rows),exact=sum(r['exact'] and (r['files']<=8 if s=='5-8' else r['files']>8) for r in rows)) for s in ('5-8','9-16')},interpretation='fixed B transfer only, does not reverse independent small-case NO-GO or change frozen D candidate/target; model failure still returns validated A2 fallback')
 result['budget_enforcement_limitation']='Inference deadline does not interrupt the subsequent mandatory temp-index audit; if total wall exceeds600, the experiment fails its resource gate. Raw partition matches are not bounded end-to-end successes.'
 with (OUT/'iteration-8-summary.json').open('x') as f:json.dump(result,f,ensure_ascii=False,indent=2);f.write('\n')
 print(json.dumps(result,ensure_ascii=False))
if __name__=='__main__':main()
